### ISSUE TITLE
La lista de usuarios es incorrecta

### ISSUE THREAD

**Issue by JJ** [JJ/IV-22-23#144]
La lista de usuarios devuelve líneas incorrectas

**Comment by arsa-dev** [comment]
¿Esta issue tiene relación con no estar aún creado el fichero para la entrega del objetivo 4? Me gustaría realizar dicha entrega durante la clase de mañana. Ya solamente me falta implementar los tests, y le estimo unos 30 minutos.

**Comment by JJ** [comment]
No, eso lo hago en unos minutos.
