### ISSUE TITLE
¿Serviría de algo consolidar todos los errores frecuentes en una sola página por objetivo?

### ISSUE THREAD

**Issue by JJ** [JJ/IV-22-23#182]

**Comment by danielsp13** [comment]
Hace tiempo leí este issue, pero quería haber alcanzado los objetivos más importantes (hasta el 4 por lo menos) para poder dar una respuesta. Definitivamente considero que sí, por los siguientes motivos:

1. Haber consultado los errores frecuentes me ha podido permitir corregir errores (sí, suena redundante, pero personalmente siento que me ha beneficiado bastante), y en posteriores entregas no cometer los errores asociados a un determinado objetivo anterior (por ejemplo, la forma de realizar commits o especificar criterios a la hora de elección de herramientas para el proyecto).
2. A partir de la semana 15 hacia atrás (hasta la semana 10), el hecho de enlazar los errores del objetivo 4 (y del objetivo 5 también) permite navegar muy bien sobre los errores y tener un acceso mucho más rápido.

Así que principalmente por este segundo motivo, considero que sí sirve. Tener los errores frecuentes ya de por sí es un complemento perfecto a la documentación que existe en la asignatura, mejor entonces si se pueden disponer de forma global para cada objetivo. Además, podría valorarse que estos documentos no dependan del curso, es decir, que sea algo común a todas las sesiones (21-22, 22-23, ...).

**Comment by JJ** [comment]
Se podría poner complementario al objetivo correspondiente. Quizás en otra página, no sé. Ya tienen más de 10 páginas cada objetivo, meter más materia no sé si es conveniente... ¿Qué crees?

**Comment by danielsp13** [comment]
Ayer le estuve dando vueltas al asunto y creo que lo más cómodo para todos sería la existencia de un único fichero, pongámosle `errores.md`, que se encuentre en el directorio de `sesiones/`. He llegado a esta conclusión nuevamente pensando en lo que yo he necesitado, y bueno, realmente no he tenido que consultar errores que se hayan producido en cursos anteriores y ha sido suficiente con hacerlo en el actual. Además, la existencia de dichos errores está motivada por lo que sucede en el mismo curso, ya sea por las propias correcciones que se hacen en los PR, o lo que surja en las sesiones de grupo dividido y común.

Así que digamos que su situación sería algo así:
~~~
sesiones/
\_ ERRORES.md
\_ semana1.md
\_ ...
\_ semana15.md
~~~

En cuanto a la estructura de este fichero, lo que se me ha ocurrido es que se disponga por objetivos, y que dentro de cada objetivo se dividan los errores en la semana en la que se produjo. Además, se puede enlazar la documentación de la semana en este fichero para que así la navegación entre documentos sea más directa y se pueda ver qué es lo que se hizo en esa clase.

En definitiva los errores frecuentes no dejan de ser un complemento, y su esencia es que son generalmente indicaciones cortas, claras y concisas, que además de que tienen el objetivo principal de evitar cometerlos, uno secundario es *no perder el norte y saber qué es lo que se está pidiendo en cada objetivo*.

Podría probar a ver cómo queda si está de acuerdo.

**Comment by JJ** [comment]
No te preocupes, para lo que queda este año no sé si merecerá la pena pegarse el trabajazo. Lo puedo tener en cuenta para años sucesivos.

**Comment by JJ** [comment]
Pero me parece buena la sugerencia. Simplemente se enlaza desde las sesiones semanales y ya está. ¡Gracias!

**Comment by JJ** [comment]
Al final se hizo en el curso siguiente. Muchas gracias por la sugerencia.
